spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_processing_db
    username: pp_user
    password: pp_user_pswd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org.zalando.logbook: TRACE

---

spring:
  config:
    activate:
      on-profile: dockerdb
  datasource:
    url: jdbc:postgresql://localhost:6000/payment_processing_db

---

spring:
  config:
    activate:
      on-profile: h2memdb
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
